version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '19001:19099'
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: ['npm', 'start']
